import { useEffect, useState, type FormEvent } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { Bell, CalendarClock, Check, Clock3, Save, UserRound } from "lucide-react";
import { apiDataRequest } from "../../services/api.client";
import { useBookings, useChargingSessions, useOperatorAlerts, useOperatorProfile } from "../../hooks/useInfrastructureOperator";
import { Button, fieldClass, PageHeader, Pagination, Panel, QueryState, SearchField, StatusBadge, UnavailableModule } from "../../components/operator/OperatorUI";

const th = "px-4 py-3 text-left text-[11px] font-semibold uppercase tracking-wide text-[#64748B]";
const td = "whitespace-nowrap px-4 py-3 text-sm text-[#111827]";
const formatDate = (value?: string | null) => value ? new Date(value).toLocaleString() : "In progress";
const money = (value?: number | null, currency = "INR") => new Intl.NumberFormat("en-IN", { style: "currency", currency, maximumFractionDigits: 2 }).format(value ?? 0);

export function ChargingReservationsPage() {
  return <><PageHeader eyebrow="Charging operations" title="Charging reservations" description="Reserved charging windows for assigned chargers." /><UnavailableModule title="Charging reservations are not available yet" description="The current schema only stores parking bookings and does not link a reservation to a charger. The operator console will not display parking bookings as charging reservations." endpoint="GET /api/v1/charging-reservations" /></>;
}

export function PricingPage() {
  return <><PageHeader eyebrow="Commercial operations" title="Pricing" description="Tariffs for charging energy, parking time, and facility-specific rules." /><UnavailableModule title="Pricing configuration requires a tariff API" description="There is no pricing or tariff model in the current schema. Pricing controls remain disabled so the frontend cannot imply that an unsaved value is active." endpoint="GET/POST /api/v1/pricing" /></>;
}

export function ChargingSessionsPage() {
  const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [status, setStatus] = useState("ALL"); const query = useChargingSessions(page);
  const rows = (query.data?.data ?? []).filter((session) => {
    const sessionStatus = session.endedAt ? "COMPLETED" : "ACTIVE";
    return (status === "ALL" || status === sessionStatus) && [session.id, session.charger?.id, session.charger?.station?.name, session.user?.name].some((value) => value?.toLowerCase().includes(search.toLowerCase()));
  });
  return <><PageHeader eyebrow="Charging operations" title="Charging sessions" description="Energy delivery sessions on chargers within your assigned stations." /><Panel><div className="flex flex-wrap gap-2 border-b border-[#E5E7EB] p-4"><SearchField value={search} onChange={setSearch} placeholder="Filter sessions" /><select aria-label="Filter session status" className="rounded-md border border-[#E5E7EB] bg-white px-3 py-2 text-sm" value={status} onChange={(e) => setStatus(e.target.value)}><option value="ALL">All statuses</option><option value="ACTIVE">Active</option><option value="COMPLETED">Completed</option></select></div><QueryState loading={query.isLoading} error={query.error} empty={!rows.length}><div className="overflow-x-auto"><table className="w-full"><thead className="bg-slate-50"><tr><th className={th}>Session</th><th className={th}>Station / charger</th><th className={th}>Driver</th><th className={th}>Started</th><th className={th}>Ended</th><th className={th}>Energy</th><th className={th}>Cost</th><th className={th}>Status</th></tr></thead><tbody className="divide-y divide-[#E5E7EB]">{rows.map((session) => <tr key={session.id}><td className={`${td} font-medium`}>{session.id}</td><td className={td}>{session.charger.station.name}<div className="mt-0.5 text-xs text-[#64748B]">{session.charger.id}</div></td><td className={td}>{session.user?.name ?? session.userId}</td><td className={td}>{formatDate(session.startedAt)}</td><td className={td}>{formatDate(session.endedAt)}</td><td className={td}>{session.energyKwh == null ? "—" : `${session.energyKwh.toFixed(2)} kWh`}</td><td className={td}>{session.cost == null ? "—" : money(session.cost)}</td><td className={td}><StatusBadge status={session.endedAt ? "COMPLETED" : "ACTIVE"} /></td></tr>)}</tbody></table></div><Pagination page={page} limit={20} total={query.data?.meta?.total} onPage={setPage} /></QueryState></Panel></>;
}

function ParkingBookingTable({ sessionsOnly }: { sessionsOnly: boolean }) {
  const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [status, setStatus] = useState("ALL"); const query = useBookings(page);
  const rows = (query.data?.data ?? []).filter((booking) => {
    const lifecycleMatch = !sessionsOnly || ["ACTIVE", "COMPLETED"].includes(booking.status);
    const statusMatch = status === "ALL" || booking.status === status;
    const searchMatch = [booking.id, booking.parkingSlot?.label, booking.parkingSlot?.location?.name, booking.user?.name].some((value) => value?.toLowerCase().includes(search.toLowerCase()));
    return lifecycleMatch && statusMatch && searchMatch;
  });
  return <Panel><div className="flex flex-wrap gap-2 border-b border-[#E5E7EB] p-4"><SearchField value={search} onChange={setSearch} placeholder={sessionsOnly ? "Filter parking sessions" : "Filter reservations"} /><select aria-label="Filter reservation status" className="rounded-md border border-[#E5E7EB] bg-white px-3 py-2 text-sm" value={status} onChange={(e) => setStatus(e.target.value)}><option value="ALL">All statuses</option>{["PENDING", "CONFIRMED", "ACTIVE", "COMPLETED", "CANCELLED"].map((value) => <option key={value}>{value}</option>)}</select></div><QueryState loading={query.isLoading} error={query.error} empty={!rows.length} emptyTitle={sessionsOnly ? "No parking sessions" : "No parking reservations"}><div className="overflow-x-auto"><table className="w-full"><thead className="bg-slate-50"><tr><th className={th}>{sessionsOnly ? "Session" : "Reservation"}</th><th className={th}>Location / bay</th><th className={th}>Driver</th><th className={th}>Start</th><th className={th}>End</th><th className={th}>Payment</th><th className={th}>Status</th></tr></thead><tbody className="divide-y divide-[#E5E7EB]">{rows.map((booking) => <tr key={booking.id}><td className={`${td} font-medium`}>{booking.id}</td><td className={td}>{booking.parkingSlot.location.name}<div className="mt-0.5 text-xs text-[#64748B]">Bay {booking.parkingSlot.label}</div></td><td className={td}>{booking.user?.name ?? booking.userId}</td><td className={td}>{formatDate(booking.startsAt)}</td><td className={td}>{formatDate(booking.endsAt)}</td><td className={td}>{booking.payment ? <>{money(booking.payment.amount, booking.payment.currency)}<div className="mt-0.5"><StatusBadge status={booking.payment.status} /></div></> : "—"}</td><td className={td}><StatusBadge status={booking.status} /></td></tr>)}</tbody></table></div><Pagination page={page} limit={20} total={query.data?.meta?.total} onPage={setPage} /></QueryState></Panel>;
}

export function ParkingReservationsPage() { return <><PageHeader eyebrow="Parking operations" title="Parking reservations" description="Bookings limited to bays within your assigned parking locations." /><ParkingBookingTable sessionsOnly={false} /></>; }
export function ParkingSessionsPage() { return <><PageHeader eyebrow="Parking operations" title="Parking sessions" description="Active and completed parking activity derived from the owned booking lifecycle." /><ParkingBookingTable sessionsOnly /></>; }

export function AlertsPage() {
  const query = useOperatorAlerts(); const client = useQueryClient();
  const markRead = useMutation({ mutationFn: (id: string) => apiDataRequest(`/notifications/${id}/read`, { method: "PATCH" }), onSuccess: async () => { await client.invalidateQueries({ queryKey: ["infrastructure-operator", "alerts"] }); } });
  const alerts = query.data ?? [];
  return <><PageHeader eyebrow="Operations awareness" title="Alerts" description="Notifications issued to your operator account." actions={<span className="rounded-full bg-red-50 px-3 py-1.5 text-xs font-semibold text-[#DC2626]">{alerts.filter((item) => !item.readAt).length} unread</span>} /><QueryState loading={query.isLoading} error={query.error} empty={!alerts.length} emptyTitle="No alerts" emptyDescription="New operational notifications will appear here."><Panel><ol className="divide-y divide-[#E5E7EB]">{alerts.map((alert) => <li key={alert.id} className="flex gap-4 p-5"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-full ${alert.readAt ? "bg-slate-100 text-[#64748B]" : "bg-red-50 text-[#DC2626]"}`}><Bell className="h-4 w-4" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-sm font-semibold">{alert.title}</h2><StatusBadge status={alert.readAt ? "READ" : "UNREAD"} /></div><p className="mt-1 text-sm leading-6 text-[#64748B]">{alert.body}</p><p className="mt-2 flex items-center gap-1 text-xs text-[#64748B]"><Clock3 className="h-3.5 w-3.5" />{formatDate(alert.createdAt)}</p></div>{!alert.readAt ? <Button variant="secondary" disabled={markRead.isPending} onClick={() => markRead.mutate(alert.id)}><Check className="h-4 w-4" />Mark read</Button> : null}</li>)}</ol></Panel></QueryState></>;
}

export function SettingsPage() {
  const query = useOperatorProfile(); const client = useQueryClient(); const [form, setForm] = useState({ name: "", phone: "" }); const [saved, setSaved] = useState(false);
  useEffect(() => { if (query.data) setForm({ name: query.data.name, phone: query.data.phone ?? "" }); }, [query.data]);
  const update = useMutation({ mutationFn: () => apiDataRequest("/users/me", { method: "PATCH", body: JSON.stringify({ name: form.name, phone: form.phone }) }), onSuccess: async () => { setSaved(true); await client.invalidateQueries({ queryKey: ["infrastructure-operator", "profile"] }); window.setTimeout(() => setSaved(false), 2500); } });
  const submit = (event: FormEvent) => { event.preventDefault(); update.mutate(); };
  return <><PageHeader eyebrow="Account" title="Settings" description="Profile settings for the authenticated infrastructure operator." /><QueryState loading={query.isLoading} error={query.error} empty={!query.data}><div className="grid gap-5 xl:grid-cols-[minmax(0,2fr)_minmax(280px,1fr)]"><Panel title="Operator profile" description="These fields are saved through the user profile API."><form onSubmit={submit} className="space-y-5 p-5"><label className="block text-sm font-medium">Name<input required minLength={2} className={fieldClass} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label className="block text-sm font-medium">Phone<input type="tel" className={fieldClass} value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></label><label className="block text-sm font-medium">Email<input readOnly className={`${fieldClass} bg-slate-50 text-[#64748B]`} value={query.data?.email ?? ""} /></label>{update.error ? <p role="alert" className="text-sm text-[#DC2626]">{update.error.message}</p> : null}<Button type="submit" disabled={update.isPending}><Save className="h-4 w-4" />{saved ? "Saved" : update.isPending ? "Saving…" : "Save changes"}</Button></form></Panel><Panel title="Access scope"><div className="p-5"><UserRound className="h-6 w-6 text-[#2563EB]" /><dl className="mt-4 space-y-4 text-sm"><div><dt className="text-[#64748B]">Application role</dt><dd className="mt-1 font-medium">Infrastructure operator</dd></div><div><dt className="text-[#64748B]">Stored role</dt><dd className="mt-1"><StatusBadge status={query.data?.role ?? "UNKNOWN"} /></dd></div><div><dt className="text-[#64748B]">Resource access</dt><dd className="mt-1 font-medium">Assigned assets only</dd></div></dl></div></Panel></div></QueryState></>;
}
