import { useMemo, useState, type FormEvent } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { Cpu, Lock, MapPin, Plus, RadioTower, RefreshCw, Trash2, Unlock, Zap } from "lucide-react";
import { apiDataRequest } from "../../services/api.client";
import { useChargerTelemetry, useChargers, useDevices, useParkingBays, useParkingLocations, useStations } from "../../hooks/useInfrastructureOperator";
import type { Charger, IoTDevice, ParkingBay, ParkingLocation, Station } from "../../types/infrastructure-operator";
import { Button, ConfirmDialog, fieldClass, KpiCard, Modal, PageHeader, Pagination, Panel, QueryState, SearchField, StatusBadge } from "../../components/operator/OperatorUI";

const th = "px-4 py-3 text-left text-[11px] font-semibold uppercase tracking-wide text-[#64748B]";
const td = "whitespace-nowrap px-4 py-3 text-sm text-[#111827]";
const formatDate = (value?: string | null) => value ? new Date(value).toLocaleString() : "Not reported";
const includes = (values: Array<string | undefined | null>, search: string) => values.some((value) => value?.toLowerCase().includes(search.toLowerCase()));

function ResourceToolbar({ search, setSearch, placeholder, onAdd, addLabel }: { search: string; setSearch: (value: string) => void; placeholder: string; onAdd?: () => void; addLabel?: string }) {
  return <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#E5E7EB] p-4"><SearchField value={search} onChange={setSearch} placeholder={placeholder} />{onAdd ? <Button onClick={onAdd}><Plus className="h-4 w-4" />{addLabel}</Button> : null}</div>;
}

export function StationsPage() {
  const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [open, setOpen] = useState(false); const [remove, setRemove] = useState<Station | null>(null);
  const [form, setForm] = useState({ name: "", address: "", latitude: "", longitude: "" });
  const query = useStations(page); const client = useQueryClient();
  const rows = (query.data?.data ?? []).filter((item) => includes([item.name, item.address], search));
  const create = useMutation({ mutationFn: () => apiDataRequest<Station>("/stations", { method: "POST", body: JSON.stringify({ name: form.name, address: form.address || undefined, latitude: Number(form.latitude), longitude: Number(form.longitude) }) }), onSuccess: async () => { setOpen(false); setForm({ name: "", address: "", latitude: "", longitude: "" }); await client.invalidateQueries({ queryKey: ["infrastructure-operator", "stations"] }); } });
  const destroy = useMutation({ mutationFn: (id: string) => apiDataRequest(`/stations/${id}`, { method: "DELETE" }), onSuccess: async () => { setRemove(null); await client.invalidateQueries({ queryKey: ["infrastructure-operator", "stations"] }); } });
  const submit = (event: FormEvent) => { event.preventDefault(); create.mutate(); };
  return <><PageHeader eyebrow="Charging infrastructure" title="Stations" description="Manage charging stations assigned to your operator account." /><Panel><ResourceToolbar search={search} setSearch={setSearch} placeholder="Filter by station or address" onAdd={() => setOpen(true)} addLabel="Add station" /><QueryState loading={query.isLoading} error={query.error} empty={!rows.length}><div className="overflow-x-auto"><table className="w-full"><thead className="bg-slate-50"><tr><th className={th}>Station</th><th className={th}>Address</th><th className={th}>Chargers</th><th className={th}>Availability</th><th className={`${th} text-right`}>Actions</th></tr></thead><tbody className="divide-y divide-[#E5E7EB]">{rows.map((station) => <tr key={station.id}><td className={td}><div className="font-medium">{station.name}</div><div className="mt-0.5 text-xs text-[#64748B]">{station.latitude.toFixed(4)}, {station.longitude.toFixed(4)}</div></td><td className={`${td} max-w-xs truncate`}>{station.address || "—"}</td><td className={td}>{station.chargers.length}</td><td className={td}><StatusBadge status={station.chargers.some((item) => item.status === "AVAILABLE") ? "AVAILABLE" : station.chargers.length ? "OFFLINE" : "NOT CONFIGURED"} /></td><td className={`${td} text-right`}><button type="button" aria-label={`Delete ${station.name}`} className="rounded p-2 text-[#64748B] hover:bg-red-50 hover:text-[#DC2626]" onClick={() => setRemove(station)}><Trash2 className="h-4 w-4" /></button></td></tr>)}</tbody></table></div><Pagination page={page} limit={20} total={query.data?.meta?.total} onPage={setPage} /></QueryState></Panel>
    <Modal open={open} title="Add charging station" description="The new station will be assigned to your operator account." onClose={() => setOpen(false)}><form onSubmit={submit} className="space-y-4"><label className="block text-sm font-medium">Station name<input required className={fieldClass} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label className="block text-sm font-medium">Address<input className={fieldClass} value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium">Latitude<input required type="number" step="any" className={fieldClass} value={form.latitude} onChange={(e) => setForm({ ...form, latitude: e.target.value })} /></label><label className="block text-sm font-medium">Longitude<input required type="number" step="any" className={fieldClass} value={form.longitude} onChange={(e) => setForm({ ...form, longitude: e.target.value })} /></label></div>{create.error ? <p role="alert" className="text-sm text-[#DC2626]">{create.error.message}</p> : null}<div className="flex justify-end gap-2"><Button variant="secondary" type="button" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" disabled={create.isPending}>Create station</Button></div></form></Modal>
    <ConfirmDialog open={Boolean(remove)} title="Delete charging station?" description={`${remove?.name ?? "This station"} and dependent chargers may be permanently removed. This command is ownership-checked by the API.`} confirmLabel="Delete station" danger busy={destroy.isPending} onCancel={() => setRemove(null)} onConfirm={() => remove && destroy.mutate(remove.id)} />
  </>;
}

export function ChargersPage() {
  const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [status, setStatus] = useState("ALL"); const [open, setOpen] = useState(false); const [remove, setRemove] = useState<Charger | null>(null);
  const [form, setForm] = useState({ stationId: "", connectorType: "CCS2", maximumPowerKw: "", status: "AVAILABLE" });
  const query = useChargers(page); const stations = useStations(1, 100); const client = useQueryClient();
  const rows = (query.data?.data ?? []).filter((item) => (status === "ALL" || item.status === status) && includes([item.id, item.station?.name, item.connectorType], search));
  const create = useMutation({ mutationFn: () => apiDataRequest<Charger>("/chargers", { method: "POST", body: JSON.stringify({ ...form, maximumPowerKw: Number(form.maximumPowerKw) }) }), onSuccess: async () => { setOpen(false); await client.invalidateQueries({ queryKey: ["infrastructure-operator", "chargers"] }); } });
  const destroy = useMutation({ mutationFn: (id: string) => apiDataRequest(`/chargers/${id}`, { method: "DELETE" }), onSuccess: async () => { setRemove(null); await client.invalidateQueries({ queryKey: ["infrastructure-operator", "chargers"] }); } });
  return <><PageHeader eyebrow="Charging infrastructure" title="Chargers" description="Configure chargers within your assigned stations and review their current operational state." /><Panel><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#E5E7EB] p-4"><div className="flex flex-wrap gap-2"><SearchField value={search} onChange={setSearch} placeholder="Filter chargers" /><select aria-label="Filter by status" className="rounded-md border border-[#E5E7EB] bg-white px-3 py-2 text-sm" value={status} onChange={(e) => setStatus(e.target.value)}><option value="ALL">All statuses</option>{["AVAILABLE", "OCCUPIED", "FAULTED", "OFFLINE"].map((value) => <option key={value}>{value}</option>)}</select></div><Button onClick={() => setOpen(true)}><Plus className="h-4 w-4" />Add charger</Button></div><QueryState loading={query.isLoading} error={query.error} empty={!rows.length}><div className="overflow-x-auto"><table className="w-full"><thead className="bg-slate-50"><tr><th className={th}>Charger</th><th className={th}>Station</th><th className={th}>Connector</th><th className={th}>Max power</th><th className={th}>Status</th><th className={`${th} text-right`}>Actions</th></tr></thead><tbody className="divide-y divide-[#E5E7EB]">{rows.map((charger) => <tr key={charger.id}><td className={`${td} font-medium`}>{charger.id}</td><td className={td}>{charger.station?.name ?? "—"}</td><td className={td}>{charger.connectorType}</td><td className={td}>{charger.maximumPowerKw} kW</td><td className={td}><StatusBadge status={charger.status} /></td><td className={`${td} text-right`}><button type="button" aria-label={`Delete charger ${charger.id}`} className="rounded p-2 text-[#64748B] hover:bg-red-50 hover:text-[#DC2626]" onClick={() => setRemove(charger)}><Trash2 className="h-4 w-4" /></button></td></tr>)}</tbody></table></div><Pagination page={page} limit={20} total={query.data?.meta?.total} onPage={setPage} /></QueryState></Panel>
    <Modal open={open} title="Add charger" description="Only stations in your assigned scope can accept this charger." onClose={() => setOpen(false)}><form onSubmit={(e) => { e.preventDefault(); create.mutate(); }} className="space-y-4"><label className="block text-sm font-medium">Station<select required className={fieldClass} value={form.stationId} onChange={(e) => setForm({ ...form, stationId: e.target.value })}><option value="">Select a station</option>{stations.data?.data.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium">Connector<select className={fieldClass} value={form.connectorType} onChange={(e) => setForm({ ...form, connectorType: e.target.value })}>{["CCS2", "CHADEMO", "TYPE2", "BHARAT_DC_001", "BHARAT_AC_001", "LEV_AC"].map((value) => <option key={value}>{value}</option>)}</select></label><label className="block text-sm font-medium">Maximum power (kW)<input required min="0.1" step="0.1" type="number" className={fieldClass} value={form.maximumPowerKw} onChange={(e) => setForm({ ...form, maximumPowerKw: e.target.value })} /></label></div><label className="block text-sm font-medium">Initial status<select className={fieldClass} value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}>{["AVAILABLE", "OCCUPIED", "OFFLINE", "FAULTED"].map((value) => <option key={value}>{value}</option>)}</select></label>{create.error ? <p role="alert" className="text-sm text-[#DC2626]">{create.error.message}</p> : null}<div className="flex justify-end gap-2"><Button variant="secondary" type="button" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" disabled={create.isPending}>Create charger</Button></div></form></Modal>
    <ConfirmDialog open={Boolean(remove)} title="Delete charger?" description={`Charger ${remove?.id ?? ""} will be permanently removed after the API confirms ownership.`} confirmLabel="Delete charger" danger busy={destroy.isPending} onCancel={() => setRemove(null)} onConfirm={() => remove && destroy.mutate(remove.id)} />
  </>;
}

export function ChargerStatusPage() {
  const chargers = useChargers(1, 100); const telemetry = useChargerTelemetry(); const [search, setSearch] = useState("");
  const snapshots = new Map((telemetry.data?.chargers ?? []).map((item) => [item.telemetry.chargerId, item]));
  const rows = (chargers.data?.data ?? []).filter((item) => includes([item.id, item.station?.name, item.status], search));
  const counts = rows.reduce((result, item) => ({ ...result, [item.status]: (result[item.status] ?? 0) + 1 }), {} as Record<string, number>);
  return <><PageHeader eyebrow="Live operations" title="Live charger status" description="Database state and normalized telemetry for chargers in your assigned stations." actions={<Button variant="secondary" onClick={() => { void chargers.refetch(); void telemetry.refetch(); }}><RefreshCw className="h-4 w-4" />Refresh</Button>} /><div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="Available" value={counts.AVAILABLE ?? 0} tone="green" /><KpiCard label="In use" value={counts.OCCUPIED ?? 0} tone="blue" /><KpiCard label="Faulted" value={counts.FAULTED ?? 0} tone="amber" /><KpiCard label="Offline" value={counts.OFFLINE ?? 0} /></div><Panel><div className="border-b border-[#E5E7EB] p-4"><SearchField value={search} onChange={setSearch} placeholder="Filter live status" /></div><QueryState loading={chargers.isLoading || telemetry.isLoading} error={chargers.error || telemetry.error} empty={!rows.length}><div className="overflow-x-auto"><table className="w-full"><thead className="bg-slate-50"><tr><th className={th}>Charger</th><th className={th}>Station</th><th className={th}>State</th><th className={th}>Power</th><th className={th}>Temperature</th><th className={th}>Reliability</th><th className={th}>Last update</th></tr></thead><tbody className="divide-y divide-[#E5E7EB]">{rows.map((charger) => { const snapshot = snapshots.get(charger.id); return <tr key={charger.id}><td className={`${td} font-medium`}>{charger.id}</td><td className={td}>{charger.station?.name}</td><td className={td}><StatusBadge status={snapshot?.reliability.status ?? charger.status} /></td><td className={td}>{snapshot?.telemetry.powerKw == null ? "—" : `${snapshot.telemetry.powerKw} kW`}</td><td className={td}>{snapshot?.telemetry.temperatureCelsius == null ? "—" : `${snapshot.telemetry.temperatureCelsius}°C`}</td><td className={td}>{snapshot ? `${snapshot.reliability.score}/100 · ${snapshot.reliability.grade}` : "No telemetry"}</td><td className={td}>{formatDate(snapshot?.receivedAt)}</td></tr>; })}</tbody></table></div></QueryState></Panel><p className="mt-3 text-xs text-[#64748B]">{telemetry.data?.disclaimer}</p></>;
}

export function ParkingLocationsPage() {
  const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [open, setOpen] = useState(false); const [form, setForm] = useState({ name: "", latitude: "", longitude: "" });
  const query = useParkingLocations(page); const client = useQueryClient(); const rows = (query.data?.data ?? []).filter((item) => includes([item.name], search));
  const create = useMutation({ mutationFn: () => apiDataRequest<ParkingLocation>("/parking/locations", { method: "POST", body: JSON.stringify({ name: form.name, latitude: Number(form.latitude), longitude: Number(form.longitude) }) }), onSuccess: async () => { setOpen(false); setForm({ name: "", latitude: "", longitude: "" }); await client.invalidateQueries({ queryKey: ["infrastructure-operator", "parking-locations"] }); } });
  return <><PageHeader eyebrow="Parking infrastructure" title="Parking locations" description="Manage parking facilities assigned to your operator account." /><Panel><ResourceToolbar search={search} setSearch={setSearch} placeholder="Filter locations" onAdd={() => setOpen(true)} addLabel="Add location" /><QueryState loading={query.isLoading} error={query.error} empty={!rows.length}><div className="overflow-x-auto"><table className="w-full"><thead className="bg-slate-50"><tr><th className={th}>Location</th><th className={th}>Coordinates</th><th className={th}>Bays</th><th className={th}>Occupied</th><th className={th}>Added</th></tr></thead><tbody className="divide-y divide-[#E5E7EB]">{rows.map((location) => { const occupied = location.slots.filter((slot) => slot.occupancies?.[0]?.occupied).length; return <tr key={location.id}><td className={`${td} font-medium`}><span className="inline-flex items-center gap-2"><MapPin className="h-4 w-4 text-[#4F46E5]" />{location.name}</span></td><td className={td}>{location.latitude.toFixed(4)}, {location.longitude.toFixed(4)}</td><td className={td}>{location.slots.length}</td><td className={td}>{occupied}</td><td className={td}>{formatDate(location.createdAt)}</td></tr>; })}</tbody></table></div><Pagination page={page} limit={20} total={query.data?.meta?.total} onPage={setPage} /></QueryState></Panel><Modal open={open} title="Add parking location" description="The location is assigned to your operator account by the backend." onClose={() => setOpen(false)}><form className="space-y-4" onSubmit={(e) => { e.preventDefault(); create.mutate(); }}><label className="block text-sm font-medium">Location name<input required className={fieldClass} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium">Latitude<input required type="number" step="any" className={fieldClass} value={form.latitude} onChange={(e) => setForm({ ...form, latitude: e.target.value })} /></label><label className="block text-sm font-medium">Longitude<input required type="number" step="any" className={fieldClass} value={form.longitude} onChange={(e) => setForm({ ...form, longitude: e.target.value })} /></label></div>{create.error ? <p role="alert" className="text-sm text-[#DC2626]">{create.error.message}</p> : null}<div className="flex justify-end gap-2"><Button variant="secondary" type="button" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" disabled={create.isPending}>Create location</Button></div></form></Modal></>;
}

export function ParkingBaysPage() {
  const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [open, setOpen] = useState(false); const [form, setForm] = useState({ locationId: "", label: "", isEvEnabled: false });
  const query = useParkingBays(page); const locations = useParkingLocations(1, 100); const client = useQueryClient(); const rows = (query.data?.data ?? []).filter((item) => includes([item.label, item.location?.name], search));
  const create = useMutation({ mutationFn: () => apiDataRequest<ParkingBay>("/parking/bays", { method: "POST", body: JSON.stringify(form) }), onSuccess: async () => { setOpen(false); setForm({ locationId: "", label: "", isEvEnabled: false }); await client.invalidateQueries({ queryKey: ["infrastructure-operator", "parking-bays"] }); } });
  return <><PageHeader eyebrow="Parking infrastructure" title="Parking bays" description="Review and configure bays within your assigned locations." /><Panel><ResourceToolbar search={search} setSearch={setSearch} placeholder="Filter bays or locations" onAdd={() => setOpen(true)} addLabel="Add bay" /><QueryState loading={query.isLoading} error={query.error} empty={!rows.length}><div className="overflow-x-auto"><table className="w-full"><thead className="bg-slate-50"><tr><th className={th}>Bay</th><th className={th}>Location</th><th className={th}>Type</th><th className={th}>Occupancy</th><th className={th}>Device</th></tr></thead><tbody className="divide-y divide-[#E5E7EB]">{rows.map((bay) => <tr key={bay.id}><td className={`${td} font-medium`}>{bay.label}</td><td className={td}>{bay.location?.name}</td><td className={td}>{bay.isEvEnabled ? <StatusBadge status="EV ENABLED" /> : "Standard"}</td><td className={td}><StatusBadge status={bay.occupancies?.[0]?.occupied ? "OCCUPIED" : "AVAILABLE"} /></td><td className={td}>{bay.device?.externalId ?? "Not paired"}</td></tr>)}</tbody></table></div><Pagination page={page} limit={50} total={query.data?.meta?.total} onPage={setPage} /></QueryState></Panel><Modal open={open} title="Add parking bay" description="Only assigned parking locations are available." onClose={() => setOpen(false)}><form className="space-y-4" onSubmit={(e) => { e.preventDefault(); create.mutate(); }}><label className="block text-sm font-medium">Parking location<select required className={fieldClass} value={form.locationId} onChange={(e) => setForm({ ...form, locationId: e.target.value })}><option value="">Select a location</option>{locations.data?.data.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="block text-sm font-medium">Bay label<input required className={fieldClass} value={form.label} onChange={(e) => setForm({ ...form, label: e.target.value })} /></label><label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={form.isEvEnabled} onChange={(e) => setForm({ ...form, isEvEnabled: e.target.checked })} className="h-4 w-4 rounded border-[#E5E7EB] text-[#2563EB]" />EV charging enabled</label>{create.error ? <p role="alert" className="text-sm text-[#DC2626]">{create.error.message}</p> : null}<div className="flex justify-end gap-2"><Button variant="secondary" type="button" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" disabled={create.isPending}>Create bay</Button></div></form></Modal></>;
}

export function OccupancyPage() {
  const query = useParkingBays(1, 100); const [search, setSearch] = useState(""); const rows = (query.data?.data ?? []).filter((item) => includes([item.label, item.location?.name], search)); const occupied = rows.filter((item) => item.occupancies?.[0]?.occupied).length;
  return <><PageHeader eyebrow="Live operations" title="Live occupancy" description="Latest occupancy observation for every bay in your assigned locations." actions={<Button variant="secondary" onClick={() => void query.refetch()}><RefreshCw className="h-4 w-4" />Refresh</Button>} /><div className="mb-5 grid gap-3 sm:grid-cols-3"><KpiCard label="Total bays" value={rows.length} tone="indigo" /><KpiCard label="Occupied" value={occupied} tone="blue" /><KpiCard label="Available" value={rows.length - occupied} tone="green" /></div><Panel><div className="border-b border-[#E5E7EB] p-4"><SearchField value={search} onChange={setSearch} placeholder="Filter occupancy" /></div><QueryState loading={query.isLoading} error={query.error} empty={!rows.length}><div className="grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-4">{rows.map((bay) => <article key={bay.id} className={`rounded-md border p-4 ${bay.occupancies?.[0]?.occupied ? "border-indigo-200 bg-indigo-50/40" : "border-green-200 bg-green-50/40"}`}><div className="flex items-start justify-between gap-2"><div><p className="font-semibold">{bay.label}</p><p className="mt-1 text-xs text-[#64748B]">{bay.location?.name}</p></div><StatusBadge status={bay.occupancies?.[0]?.occupied ? "OCCUPIED" : "AVAILABLE"} /></div><p className="mt-4 text-xs text-[#64748B]">Observed {formatDate(bay.occupancies?.[0]?.observedAt)}</p></article>)}</div></QueryState></Panel></>;
}

function deviceHealth(device: IoTDevice) { if (!device.lastSeenAt) return "OFFLINE"; return Date.now() - new Date(device.lastSeenAt).getTime() <= 5 * 60_000 ? "HEALTHY" : "STALE"; }

export function DevicesPage({ healthOnly = false }: { healthOnly?: boolean }) {
  const query = useDevices(1, 100); const [search, setSearch] = useState(""); const rows = (query.data?.data ?? []).filter((item) => includes([item.id, item.externalId, item.parkingSlot?.label, item.parkingSlot?.location?.name], search)); const healthy = rows.filter((item) => deviceHealth(item) === "HEALTHY").length;
  return <><PageHeader eyebrow="Connected infrastructure" title={healthOnly ? "Device health" : "IoT devices"} description={healthOnly ? "Heartbeat freshness and assignment state for owned devices." : "Inventory of connected devices paired to bays in your assigned locations."} actions={<Button variant="secondary" onClick={() => void query.refetch()}><RefreshCw className="h-4 w-4" />Refresh</Button>} />{healthOnly ? <div className="mb-5 grid gap-3 sm:grid-cols-3"><KpiCard label="Healthy" value={healthy} tone="green" /><KpiCard label="Stale" value={rows.filter((item) => deviceHealth(item) === "STALE").length} tone="amber" /><KpiCard label="Offline" value={rows.filter((item) => deviceHealth(item) === "OFFLINE").length} /></div> : null}<Panel><div className="border-b border-[#E5E7EB] p-4"><SearchField value={search} onChange={setSearch} placeholder="Filter devices" /></div><QueryState loading={query.isLoading} error={query.error} empty={!rows.length}><div className="overflow-x-auto"><table className="w-full"><thead className="bg-slate-50"><tr><th className={th}>Device</th><th className={th}>Location</th><th className={th}>Bay</th><th className={th}>Health</th><th className={th}>Last heartbeat</th></tr></thead><tbody className="divide-y divide-[#E5E7EB]">{rows.map((device) => <tr key={device.id}><td className={td}><span className="inline-flex items-center gap-2 font-medium"><Cpu className="h-4 w-4 text-[#0F766E]" />{device.externalId}</span><div className="mt-0.5 text-xs text-[#64748B]">{device.id}</div></td><td className={td}>{device.parkingSlot?.location?.name ?? "Unassigned"}</td><td className={td}>{device.parkingSlot?.label ?? "—"}</td><td className={td}><StatusBadge status={deviceHealth(device)} /></td><td className={td}>{formatDate(device.lastSeenAt)}</td></tr>)}</tbody></table></div></QueryState></Panel></>;
}

export function SmartLocksPage() {
  const query = useDevices(1, 100); const [selected, setSelected] = useState<{ device: IoTDevice; command: "lock" | "unlock" } | null>(null); const client = useQueryClient();
  const command = useMutation({ mutationFn: ({ device, command }: NonNullable<typeof selected>) => apiDataRequest(`/iot/devices/${device.id}/${command}`, { method: "POST", body: JSON.stringify({}) }), onSuccess: async () => { setSelected(null); await client.invalidateQueries({ queryKey: ["infrastructure-operator", "devices"] }); } });
  return <><PageHeader eyebrow="Infrastructure control" title="Smart lock control" description="Issue lock and unlock commands through ownership-checked backend APIs." /><div className="mb-4 rounded-md border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-[#92400E]">Every command requires confirmation and is authorized against the device's assigned parking location.</div><QueryState loading={query.isLoading} error={query.error} empty={!query.data?.data.length}><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{query.data?.data.map((device) => <Panel key={device.id} className="p-5"><div className="flex items-start justify-between"><div><RadioTower className="h-5 w-5 text-[#0F766E]" /><h2 className="mt-3 font-semibold">{device.externalId}</h2><p className="mt-1 text-sm text-[#64748B]">{device.parkingSlot?.location?.name} · {device.parkingSlot?.label}</p></div><StatusBadge status={deviceHealth(device)} /></div><div className="mt-5 grid grid-cols-2 gap-2"><Button variant="secondary" disabled={deviceHealth(device) === "OFFLINE"} onClick={() => setSelected({ device, command: "lock" })}><Lock className="h-4 w-4" />Lock</Button><Button disabled={deviceHealth(device) === "OFFLINE"} onClick={() => setSelected({ device, command: "unlock" })}><Unlock className="h-4 w-4" />Unlock</Button></div></Panel>)}</div></QueryState><ConfirmDialog open={Boolean(selected)} title={`${selected?.command === "unlock" ? "Unlock" : "Lock"} smart lock?`} description={`Send a ${selected?.command ?? "control"} command to ${selected?.device.externalId ?? "this device"}. The backend will verify assignment before execution.`} confirmLabel={selected?.command === "unlock" ? "Send unlock" : "Send lock"} busy={command.isPending} onCancel={() => setSelected(null)} onConfirm={() => selected && command.mutate(selected)} /></>;
}
