import type { StationProvider, StationRecord } from "./station.provider.js";

export const DEMO_STATIONS: StationRecord[] = [
  {
    id: "station-demo-1",
    name: "VoltTwin Central Hub",
    latitude: 19.076,
    longitude: 72.8777,
    availableChargers: 3,
    powerKw: 60,
    reliabilityScore: 94,
    pricePerKwh: 18,
    estimatedWaitMinutes: 4,
    sourceMode: "DEMO",
    isSimulated: true,
    chargers: [
      {
        id: "charger-demo-1-ccs2",
        connectorType: "CCS2",
        status: "AVAILABLE",
        powerKw: 60,
        pricePerKwh: 18,
        reliabilityBaseline: {
          uptimePercent: 97,
          successfulSessionsPercent: 95,
          heartbeatFreshnessPercent: 98,
          faultRatePercent: 2,
          recentFaultCount: 0,
          temperatureCelsius: 34,
          telemetryCompletenessPercent: 92,
          sourceMode: "DEMO",
        },
      },
      {
        id: "charger-demo-1-type2",
        connectorType: "TYPE2",
        status: "CHARGING",
        powerKw: 22,
        pricePerKwh: 16,
        reliabilityBaseline: {
          uptimePercent: 94,
          successfulSessionsPercent: 92,
          heartbeatFreshnessPercent: 96,
          faultRatePercent: 4,
          recentFaultCount: 0,
          temperatureCelsius: 37,
          telemetryCompletenessPercent: 90,
          sourceMode: "DEMO",
        },
      },
      {
        id: "charger-demo-1-lev",
        connectorType: "LEV_AC",
        status: "AVAILABLE",
        powerKw: 7.2,
        pricePerKwh: 12,
        reliabilityBaseline: {
          uptimePercent: 93,
          successfulSessionsPercent: 91,
          heartbeatFreshnessPercent: 95,
          faultRatePercent: 4,
          recentFaultCount: 0,
          temperatureCelsius: 31,
          telemetryCompletenessPercent: 88,
          sourceMode: "DEMO",
        },
      },
    ],
  },
  {
    id: "station-demo-2",
    name: "GreenRoute Charging Point",
    latitude: 19.1136,
    longitude: 72.8697,
    availableChargers: 1,
    powerKw: 30,
    reliabilityScore: 82,
    pricePerKwh: 15,
    estimatedWaitMinutes: 7,
    sourceMode: "DEMO",
    isSimulated: true,
    chargers: [
      {
        id: "charger-demo-2-ccs2",
        connectorType: "CCS2",
        status: "AVAILABLE",
        powerKw: 30,
        pricePerKwh: 15,
        reliabilityBaseline: {
          uptimePercent: 90,
          successfulSessionsPercent: 88,
          heartbeatFreshnessPercent: 94,
          faultRatePercent: 7,
          recentFaultCount: 1,
          temperatureCelsius: 35,
          telemetryCompletenessPercent: 86,
          sourceMode: "DEMO",
        },
      },
      {
        id: "charger-demo-2-bharat",
        connectorType: "BHARAT_DC_001",
        status: "AVAILABLE",
        powerKw: 25,
        pricePerKwh: 14,
        reliabilityBaseline: {
          uptimePercent: 89,
          successfulSessionsPercent: 87,
          heartbeatFreshnessPercent: 93,
          faultRatePercent: 8,
          recentFaultCount: 1,
          temperatureCelsius: 33,
          telemetryCompletenessPercent: 84,
          sourceMode: "DEMO",
        },
      },
      {
        id: "charger-demo-2-lev",
        connectorType: "LEV_AC",
        status: "AVAILABLE",
        powerKw: 7.2,
        pricePerKwh: 11,
        reliabilityBaseline: {
          uptimePercent: 88,
          successfulSessionsPercent: 86,
          heartbeatFreshnessPercent: 92,
          faultRatePercent: 8,
          recentFaultCount: 1,
          temperatureCelsius: 32,
          telemetryCompletenessPercent: 82,
          sourceMode: "DEMO",
        },
      },
    ],
  },
];

export class DemoStationProvider implements StationProvider {
  async listStations(): Promise<StationRecord[]> {
    return DEMO_STATIONS;
  }
}
